Merge in a bunch of changes made on a (private) version of this code.

diff --git a/containers/qdlaravel-console/configure_00_envcheck b/containers/qdlaravel-console/configure_00_envcheck
--- a/containers/qdlaravel-console/configure_00_envcheck
+++ b/containers/qdlaravel-console/configure_00_envcheck
@@ -4,3 +4,9 @@
 #        echo "\$HOSTDEF not set; aborting."
 #        exit 1
 #fi
+
+echo "** NODEVERSION is ${NODEVERSION}"
+if [ -z "${NODEVERSION}" ]; then
+        echo "\${NODEVERSION} not set; aborting."
+        exit 1
+fi
